### ISSUE TITLE
feat:Task details - Add compute resource configuration

### ISSUE THREAD

**Issue by Ark-kun** [Cloud-Pipelines/pipeline-studio-app#155]
When configuring a task, the user should be able to specify compute resource requests:
CPU: 62 (cores)
Memory: 64 (GB)
GPU (Accelerator): "nvidia-a100-80gb": 4

For GPUs there should be a combo-box with predefined list of GPUs

Some GPUs:

```
nvidia-a100-80gb       NVIDIA A100 80GB
nvidia-h100-80gb       NVIDIA H100 80GB
nvidia-h100-mega-80gb  NVIDIA H100 80GB MEGA
nvidia-l4              NVIDIA L4
nvidia-tesla-a100      NVIDIA A100 40GB
nvidia-tesla-p4        NVIDIA Tesla P4
nvidia-tesla-t4        NVIDIA T4
nvidia-tesla-v100      NVIDIA V100
```

The resource requests should be stored in task annotations:

```
annotations:
    cloud-pipelines.net/launchers/generic/resources.cpu: "2"
    cloud-pipelines.net/launchers/generic/resources.memory: "512Gi"
    cloud-pipelines.net/launchers/generic/resources.accelerators: '{"nvidia-a100-80gb": 4}'
```
