### ISSUE TITLE
Task Resource Requirements - Add "Use spot VM" and "Showback" configuration

### ISSUE THREAD

**Issue by Ark-kun** [Cloud-Pipelines/pipeline-studio-app#307]
`cloud-pipelines.net/launchers/kubernetes/google/use_spot_vms` - "Use spot VM" checkbox

`shopify.io/showback_cost_owner_ref` - "Showback cost owner" text box.

P.S. Later let's think of a solution to only show `shopify.io/showback_cost_owner_ref` to users inside Shopify. Maybe we can have a YAML file where we list well-know annotation keys and their human-readable descriptions. than we can augment that file during build/deployment.

```yaml
well_known_annotations:
  - key: shopify.io/showback_cost_owner_ref
    text: "Showback cost owner"
    type: String
  - key: cloud-pipelines.net/launchers/kubernetes/google/use_spot_vms
    text: "Use spot VM"
    type: Boolean
```

or we can use JsonSchema for this:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "cloud-pipelines.net/launchers/generic/resources.cpu": {
      "type": "integer",
      "description": "Number of CPUs",
      "minimum": 1
    },
    "cloud-pipelines.net/launchers/generic/resources.memory": {
      "type": "string",
      "description": "Memory requirement",
      "pattern": "^[0-9]+[MGT]iB$"
    },
    "cloud-pipelines.net/launchers/generic/resources.accelerators": {
      "type": "object",
      "description": "GPUs",
      "patternProperties": {
        "^.*$": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "cloud-pipelines.net/launchers/kubernetes/google/use_spot_vms": {
      "type": "boolean",
      "description": "Whether to use spot VMs"
    },
    "shopify.io/showback_cost_owner_ref": {
      "type": "string",
      "description": "Team responsible for costs"
    }
  }
}

```
